version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
          - "eslint-*"
      next:
        patterns:
          - "next"
          - "@next/*"
      nest:
        patterns:
          - "@nestjs/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
