import { UserRole } from '@ac/types';

export interface SeedPermissionDef {
  key: string;
  resource: string;
  action: string;
  description: string;
}

export const SEED_PERMISSIONS: Array<{ key: string; resource: string; action: string; description: string }> = [
  // Leads
  { key: 'lead:create', resource: 'lead', action: 'create', description: 'Create leads' },
  { key: 'lead:view', resource: 'lead', action: 'view', description: 'View leads' },
  { key: 'lead:update', resource: 'lead', action: 'update', description: 'Update leads' },
  { key: 'lead:assign', resource: 'lead', action: 'assign', description: 'Assign leads to users' },
  { key: 'lead:delete', resource: 'lead', action: 'delete', description: 'Delete leads' },
  // Bookings
  { key: 'booking:read', resource: 'booking', action: 'read', description: 'View bookings' },
  { key: 'booking:write', resource: 'booking', action: 'write', description: 'Create / edit bookings' },
  { key: 'booking:create', resource: 'booking', action: 'create', description: 'Create bookings' },
  { key: 'booking:update', resource: 'booking', action: 'update', description: 'Update bookings' },
  { key: 'booking:assign', resource: 'booking', action: 'assign', description: 'Assign technician to booking' },
  { key: 'booking:cancel', resource: 'booking', action: 'cancel', description: 'Cancel bookings' },
  { key: 'booking:reschedule', resource: 'booking', action: 'reschedule', description: 'Reschedule bookings' },
  // Customers
  { key: 'customer:read', resource: 'customer', action: 'read', description: 'View customers' },
  { key: 'customer:write', resource: 'customer', action: 'write', description: 'Create / edit customers' },
  // Technicians
  { key: 'technician:read', resource: 'technician', action: 'read', description: 'View technicians' },
  { key: 'technician:write', resource: 'technician', action: 'write', description: 'Create / edit technicians' },
  { key: 'technician:onboard', resource: 'technician', action: 'onboard', description: 'Onboard new technicians' },
  { key: 'technician:track', resource: 'technician', action: 'track', description: 'View live technician location' },
  { key: 'technician:location:write', resource: 'technician', action: 'location:write', description: 'Upload GPS pings' },
  { key: 'technician:status:write', resource: 'technician', action: 'status:write', description: 'Change availability status' },
  // Dispatch
  { key: 'dispatch:view', resource: 'dispatch', action: 'view', description: 'View dispatch control center' },
  { key: 'dispatch:assign', resource: 'dispatch', action: 'assign', description: 'Trigger auto / manual assignment' },
  { key: 'dispatch:override', resource: 'dispatch', action: 'override', description: 'Override / reassign jobs' },
  { key: 'dispatch:acknowledge', resource: 'dispatch', action: 'acknowledge', description: 'Acknowledge dispatch alerts' },
  // Finance — invoice
  { key: 'invoice:view', resource: 'invoice', action: 'view', description: 'View invoices' },
  { key: 'invoice:create', resource: 'invoice', action: 'create', description: 'Create invoices' },
  { key: 'invoice:update', resource: 'invoice', action: 'update', description: 'Edit invoices' },
  { key: 'invoice:send', resource: 'invoice', action: 'send', description: 'Send invoices to customers' },
  { key: 'invoice:cancel', resource: 'invoice', action: 'cancel', description: 'Cancel / void invoices' },
  { key: 'invoice:refund', resource: 'invoice', action: 'refund', description: 'Issue invoice refunds' },
  // Finance — quotation
  { key: 'quotation:view', resource: 'quotation', action: 'view', description: 'View quotations' },
  { key: 'quotation:create', resource: 'quotation', action: 'create', description: 'Create quotations' },
  { key: 'quotation:send', resource: 'quotation', action: 'send', description: 'Send quotations to customers' },
  { key: 'quotation:convert', resource: 'quotation', action: 'convert', description: 'Convert quotation → invoice' },
  // Finance — payment
  { key: 'payment:view', resource: 'payment', action: 'view', description: 'View payment history' },
  { key: 'payment:manage', resource: 'payment', action: 'manage', description: 'Create payment links / record manual payments' },
  { key: 'payment:refund', resource: 'payment', action: 'refund', description: 'Initiate payment refunds' },
  // Finance — AMC
  { key: 'amc:view', resource: 'amc', action: 'view', description: 'View AMC plans + subscriptions' },
  { key: 'amc:manage', resource: 'amc', action: 'manage', description: 'Manage AMC plans + subscriptions' },
  { key: 'amc:subscribe', resource: 'amc', action: 'subscribe', description: 'Subscribe / cancel as a customer' },
  // Finance — payout
  { key: 'payout:view', resource: 'payout', action: 'view', description: 'View technician payouts' },
  { key: 'payout:approve', resource: 'payout', action: 'approve', description: 'Approve payouts for processing' },
  { key: 'payout:process', resource: 'payout', action: 'process', description: 'Mark payouts paid / failed' },
  // Finance — dashboards / reports / ledger
  { key: 'finance:view', resource: 'finance', action: 'view', description: 'View finance analytics dashboard' },
  { key: 'finance:report:export', resource: 'finance', action: 'report:export', description: 'Export financial reports' },
  { key: 'ledger:view', resource: 'ledger', action: 'view', description: 'View customer ledger + statements' },
  // Invoicing & Payments
  { key: 'invoice:read', resource: 'invoice', action: 'read', description: 'View invoices' },
  { key: 'invoice:write', resource: 'invoice', action: 'write', description: 'Create / edit invoices' },
  { key: 'payment:read', resource: 'payment', action: 'read', description: 'View payments' },
  // Admin
  { key: 'user:manage', resource: 'user', action: 'manage', description: 'Manage users' },
  { key: 'role:manage', resource: 'role', action: 'manage', description: 'Manage roles' },
  { key: 'analytics:view', resource: 'analytics', action: 'view', description: 'View analytics dashboards' },
  { key: 'audit_log:view', resource: 'audit_log', action: 'view', description: 'View audit logs' },
  { key: 'notification:view', resource: 'notification', action: 'view', description: 'View notification delivery logs' },
  { key: 'notification:retry', resource: 'notification', action: 'retry', description: 'Retry failed notifications' },
  { key: 'workflow:view', resource: 'workflow', action: 'view', description: 'View workflow instances and analytics' },
  { key: 'workflow:manage', resource: 'workflow', action: 'manage', description: 'Pause, resume, and cancel workflows' },
  { key: 'automation:manage', resource: 'automation', action: 'manage', description: 'Manage automation rules and event replay' },
  { key: 'city:manage', resource: 'city', action: 'manage', description: 'Manage cities' },
  // Inventory / ERP
  { key: 'inventory:view', resource: 'inventory', action: 'view', description: 'View catalogue + stock levels' },
  { key: 'inventory:manage', resource: 'inventory', action: 'manage', description: 'Create / edit catalogue items' },
  { key: 'inventory:adjust', resource: 'inventory', action: 'adjust', description: 'Adjust stock with reason (write-off, count correction)' },
  { key: 'warehouse:view', resource: 'warehouse', action: 'view', description: 'View warehouses + zones' },
  { key: 'warehouse:manage', resource: 'warehouse', action: 'manage', description: 'Create / edit warehouses + zones' },
  { key: 'stock_transfer:view', resource: 'stock_transfer', action: 'view', description: 'View stock transfers' },
  { key: 'stock_transfer:request', resource: 'stock_transfer', action: 'request', description: 'Request a stock transfer' },
  { key: 'stock_transfer:approve', resource: 'stock_transfer', action: 'approve', description: 'Approve / reject a transfer' },
  { key: 'stock_transfer:dispatch', resource: 'stock_transfer', action: 'dispatch', description: 'Mark transfer as dispatched (source-side)' },
  { key: 'stock_transfer:receive', resource: 'stock_transfer', action: 'receive', description: 'Receive a transfer (destination-side)' },
  { key: 'vendor:view', resource: 'vendor', action: 'view', description: 'View vendors' },
  { key: 'vendor:manage', resource: 'vendor', action: 'manage', description: 'Create / edit vendors' },
  { key: 'purchase_order:view', resource: 'purchase_order', action: 'view', description: 'View purchase orders' },
  { key: 'purchase_order:create', resource: 'purchase_order', action: 'create', description: 'Draft purchase orders' },
  { key: 'purchase_order:approve', resource: 'purchase_order', action: 'approve', description: 'Approve / release POs' },
  { key: 'purchase_order:receive', resource: 'purchase_order', action: 'receive', description: 'Post Goods Receipts against a PO' },
  { key: 'purchase_order:cancel', resource: 'purchase_order', action: 'cancel', description: 'Cancel a PO' },
  { key: 'tech_inventory:view', resource: 'tech_inventory', action: 'view', description: 'View technician van inventory' },
  { key: 'tech_inventory:allocate', resource: 'tech_inventory', action: 'allocate', description: 'Allocate stock to technicians' },
  { key: 'tech_inventory:use', resource: 'tech_inventory', action: 'use', description: 'Record stock usage on bookings' },
  { key: 'tech_inventory:return', resource: 'tech_inventory', action: 'return', description: 'Return unused stock to warehouse' },
  { key: 'tech_inventory:reconcile', resource: 'tech_inventory', action: 'reconcile', description: 'Reconcile technician inventory shortfalls' },
  { key: 'inventory_alert:view', resource: 'inventory_alert', action: 'view', description: 'View inventory alerts' },
  { key: 'inventory_alert:acknowledge', resource: 'inventory_alert', action: 'acknowledge', description: 'Acknowledge / resolve inventory alerts' },
  { key: 'inventory_analytics:view', resource: 'inventory_analytics', action: 'view', description: 'View inventory analytics dashboards' },
  // Omnichannel Support / Ticketing
  { key: 'support:view', resource: 'support', action: 'view', description: 'View support dashboards and inbox' },
  { key: 'ticket:view', resource: 'ticket', action: 'view', description: 'View support tickets' },
  { key: 'ticket:create', resource: 'ticket', action: 'create', description: 'Create support tickets' },
  { key: 'ticket:update', resource: 'ticket', action: 'update', description: 'Update support ticket fields' },
  { key: 'ticket:assign', resource: 'ticket', action: 'assign', description: 'Assign tickets to agents / teams' },
  { key: 'ticket:escalate', resource: 'ticket', action: 'escalate', description: 'Escalate tickets up the chain' },
  { key: 'ticket:close', resource: 'ticket', action: 'close', description: 'Resolve and close tickets' },
  { key: 'ticket:reopen', resource: 'ticket', action: 'reopen', description: 'Reopen closed tickets' },
  { key: 'ticket:delete', resource: 'ticket', action: 'delete', description: 'Delete (soft) tickets' },
  { key: 'ticket:merge', resource: 'ticket', action: 'merge', description: 'Merge tickets' },
  { key: 'inbox:view', resource: 'inbox', action: 'view', description: 'View omnichannel inbox' },
  { key: 'inbox:manage', resource: 'inbox', action: 'manage', description: 'Reassign + resolve conversations from inbox' },
  { key: 'conversation:view', resource: 'conversation', action: 'view', description: 'View conversation threads' },
  { key: 'conversation:reply', resource: 'conversation', action: 'reply', description: 'Reply on conversations across channels' },
  { key: 'conversation:assign', resource: 'conversation', action: 'assign', description: 'Assign conversations to agents' },
  { key: 'call:view', resource: 'call', action: 'view', description: 'View call logs and recordings' },
  { key: 'call:manage', resource: 'call', action: 'manage', description: 'Manage call routing and queues' },
  { key: 'call:make', resource: 'call', action: 'make', description: 'Place outbound (click-to-call) calls' },
  { key: 'call:disposition', resource: 'call', action: 'disposition', description: 'Set call dispositions' },
  { key: 'kb:view', resource: 'kb', action: 'view', description: 'View knowledge base articles' },
  { key: 'kb:write', resource: 'kb', action: 'write', description: 'Author knowledge base articles' },
  { key: 'kb:publish', resource: 'kb', action: 'publish', description: 'Publish / archive KB articles' },
  { key: 'canned_response:view', resource: 'canned_response', action: 'view', description: 'View canned responses' },
  { key: 'canned_response:manage', resource: 'canned_response', action: 'manage', description: 'Manage canned responses' },
  { key: 'sla:view', resource: 'sla', action: 'view', description: 'View SLA profiles' },
  { key: 'sla:manage', resource: 'sla', action: 'manage', description: 'Manage SLA profiles' },
  { key: 'support_analytics:view', resource: 'support_analytics', action: 'view', description: 'View support analytics dashboards' },
  { key: '*', resource: '*', action: '*', description: 'Wildcard — full access' },
];

/**
 * Role -> permission matrix. Tweak here, never hard-code permission checks
 * in app code; always check via `@ac/auth`.
 */
export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: [
    'lead:create',
    'lead:view',
    'lead:update',
    'lead:assign',
    'lead:delete',
    'booking:read',
    'booking:write',
    'booking:create',
    'booking:update',
    'booking:assign',
    'booking:cancel',
    'booking:reschedule',
    'customer:read',
    'customer:write',
    'technician:read',
    'technician:write',
    'technician:onboard',
    'user:manage',
    'role:manage',
    'technician:track',
    'technician:status:write',
    'dispatch:view',
    'dispatch:assign',
    'dispatch:override',
    'dispatch:acknowledge',
    'invoice:view',
    'invoice:create',
    'invoice:update',
    'invoice:send',
    'invoice:cancel',
    'invoice:refund',
    'quotation:view',
    'quotation:create',
    'quotation:send',
    'quotation:convert',
    'payment:view',
    'payment:manage',
    'payment:refund',
    'amc:view',
    'amc:manage',
    'payout:view',
    'payout:approve',
    'payout:process',
    'finance:view',
    'finance:report:export',
    'ledger:view',
    'analytics:view',
    'audit_log:view',
    'notification:view',
    'notification:retry',
    'workflow:view',
    'workflow:manage',
    'automation:manage',
    'city:manage',
    'inventory:view',
    'inventory:manage',
    'inventory:adjust',
    'warehouse:view',
    'warehouse:manage',
    'stock_transfer:view',
    'stock_transfer:request',
    'stock_transfer:approve',
    'stock_transfer:dispatch',
    'stock_transfer:receive',
    'vendor:view',
    'vendor:manage',
    'purchase_order:view',
    'purchase_order:create',
    'purchase_order:approve',
    'purchase_order:receive',
    'purchase_order:cancel',
    'tech_inventory:view',
    'tech_inventory:allocate',
    'tech_inventory:use',
    'tech_inventory:return',
    'tech_inventory:reconcile',
    'inventory_alert:view',
    'inventory_alert:acknowledge',
    'inventory_analytics:view',
    'support:view',
    'ticket:view',
    'ticket:create',
    'ticket:update',
    'ticket:assign',
    'ticket:escalate',
    'ticket:close',
    'ticket:reopen',
    'ticket:delete',
    'ticket:merge',
    'inbox:view',
    'inbox:manage',
    'conversation:view',
    'conversation:reply',
    'conversation:assign',
    'call:view',
    'call:manage',
    'call:make',
    'call:disposition',
    'kb:view',
    'kb:write',
    'kb:publish',
    'canned_response:view',
    'canned_response:manage',
    'sla:view',
    'sla:manage',
    'support_analytics:view',
  ],
  DISPATCHER: [
    'lead:view',
    'lead:update',
    'lead:assign',
    'booking:read',
    'booking:write',
    'booking:create',
    'booking:update',
    'booking:assign',
    'booking:cancel',
    'booking:reschedule',
    'customer:read',
    'technician:read',
    'technician:track',
    'dispatch:view',
    'dispatch:assign',
    'dispatch:override',
    'dispatch:acknowledge',
    'invoice:view',
    'invoice:create',
    'invoice:send',
    'quotation:view',
    'quotation:create',
    'quotation:send',
    'quotation:convert',
    'payment:view',
    'payment:manage',
    'amc:view',
    'amc:manage',
    'payout:view',
    'payout:approve',
    'payout:process',
    'ledger:view',
    'finance:view',
    'analytics:view',
    'inventory:view',
    'warehouse:view',
    'stock_transfer:view',
    'stock_transfer:request',
    'stock_transfer:dispatch',
    'stock_transfer:receive',
    'vendor:view',
    'purchase_order:view',
    'tech_inventory:view',
    'tech_inventory:allocate',
    'tech_inventory:reconcile',
    'inventory_alert:view',
    'inventory_alert:acknowledge',
    'inventory_analytics:view',
    'support:view',
    'ticket:view',
    'ticket:create',
    'ticket:update',
    'ticket:assign',
    'ticket:escalate',
    'ticket:close',
    'inbox:view',
    'inbox:manage',
    'conversation:view',
    'conversation:reply',
    'conversation:assign',
    'call:view',
    'call:manage',
    'call:disposition',
    'kb:view',
    'canned_response:view',
    'sla:view',
    'support_analytics:view',
  ],
  CALL_CENTER_AGENT: [
    'lead:create',
    'lead:view',
    'lead:update',
    'booking:read',
    'booking:write',
    'booking:create',
    'customer:read',
    'customer:write',
    'technician:read',
    'quotation:view',
    'quotation:create',
    'quotation:send',
    'invoice:view',
    'amc:view',
    'amc:subscribe',
    'support:view',
    'ticket:view',
    'ticket:create',
    'ticket:update',
    'ticket:close',
    'ticket:reopen',
    'inbox:view',
    'conversation:view',
    'conversation:reply',
    'call:view',
    'call:make',
    'call:disposition',
    'kb:view',
    'canned_response:view',
  ],
  TECHNICIAN: [
    'booking:read',
    'booking:update',
    'technician:location:write',
    'technician:status:write',
    'payout:view',
    'tech_inventory:view',
    'tech_inventory:use',
    'tech_inventory:return',
    'inventory:view',
    'ticket:view',
    'conversation:view',
    'conversation:reply',
    'kb:view',
  ],
  CUSTOMER: ['amc:subscribe', 'ticket:view', 'ticket:create', 'kb:view'],
};

export const SYSTEM_ROLE_KEYS = Object.keys(ROLE_PERMISSIONS) as UserRole[];
